### ISSUE TITLE
Fix text-color of the sub label

### ISSUE THREAD

**Issue by lucazambon** [Mottie/Darker-Medium#5]
* **Google Chrome v.65.0.3325.181**:
* **Mac OS High Sierra v.10.13.4**:
* **https://medium.com/**:

The extension works perfectly except for the article's sub label.
Check the image:

![schermata 2018-04-05 alle 12 40 15](https://user-images.githubusercontent.com/35226809/38361704-926d3e30-38ce-11e8-9a96-cb842ca00e28.png)

The label color should be white i think.

**Comment by Mottie** [comment]
Hi @lucazambon!

Thanks for letting me know! I'll have it fixed shortly. The Chrome/Opera/Firefox updates will be in progress.

**Comment by lucazambon** [comment]
Good job!
