### ISSUE TITLE
Transparent image issue

### ISSUE THREAD

**Issue by zmni** [Mottie/Darker-Medium#9]
* **Browser**: Firefox x64
* **Operating System**: Windows 8.1
* **URL of the problem page**: 
    * https://medium.com/square-corner-blog/open-sourcing-subzero-ee9e3e071827#cbe9
    * https://medium.com/square-corner-blog/open-sourcing-subzero-ee9e3e071827#d95c

![1](https://user-images.githubusercontent.com/841523/47353156-c83b8980-d6e5-11e8-89ca-8eeacab51fff.png)
![2](https://user-images.githubusercontent.com/841523/47353157-c8d42000-d6e5-11e8-864d-d61c79656d1a.png)

**Comment by Mottie** [comment]
Hi @zmni!

Thanks for reporting this issue. I'll get it fixed in the next release.
